### ISSUE TITLE
能否添加更多的bilibiliapi

### ISSUE THREAD

**Issue by haishen668** [Shadow403/nonebot_plugin_BiliRequestAll#11]
查看直播间信息之类的,高能榜在线人数,多少人看过,直播间开播状态

**Comment by Shadow403** [comment]
API站 https://api-dev.shadow403.cn/docs/BiliAPI/%E7%9B%B4%E6%92%AD.html

**Comment by haishen668** [comment]
大哥高效率阿！！！
