### ISSUE TITLE
功能建议：未满足条件加群请求的自动拒绝

### ISSUE THREAD

**Issue by Dr-WeiAL** [Shadow403/nonebot_plugin_BiliRequestAll#4]
实际测试下来如果发送的验证消息里的uid未满足条件，这个加群请求就会一直不处理
是否可以添加一个配置项让未满足条件的加群请求自动拒绝并说明原因？

**Comment by Shadow403** [comment]
目前并未有想法做拒绝，不满足条件的用户等待人工审核

**Comment by Dr-WeiAL** [comment]
> 目前并未有想法做拒绝，不满足条件的用户等待人工审核

就是说添加一个 【群审核自动拒绝开关】 默认把自动拒绝关闭，有自动拒绝需求的手动打开
