### ISSUE TITLE
功能建议：审核日志统计

### ISSUE THREAD

**Issue by Dr-WeiAL** [Shadow403/nonebot_plugin_BiliRequestAll#5]
- 审批统计：在switcher_group目录下生成对应群号的表格文档，统计通过的加群请求的[QQ号/B站UID/B站ID/粉丝牌等级/审批日期]等信息
- 插件日志：处理的所有加群请求信息，包括未满足条件的加群请求

**Comment by Shadow403** [comment]
已更新

**Comment by Shadow403** [comment]
此功能已更新

**Comment by Dr-WeiAL** [comment]
好的作者辛苦了
看样子上面提到的 插件日志 更新了一部分，审批统计 是还在计划中吗？

**Comment by Shadow403** [comment]
> 好的作者辛苦了
> 
> 看样子上面提到的 插件日志 更新了一部分，审批统计 是还在计划中吗？

当然，不过要过一段时间
